name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js for frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Configure npm to use GitHub token for private packages
    - name: Configure npm for GitHub Packages
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

    # Install dependencies for frontend
    - name: Install frontend dependencies
      run: npm install

    # Build the frontend
    - name: Build frontend
      env:
        DEW_QR_API_URL: "http://your-production-api-url.com"
      run: npm run build

    # Configure Git user identity for gh-pages
    - name: Configure Git user
      env:
        GIT_USER: ${{ secrets.GITHUB_ACTOR }}
      run: |
        git config --global user.email "celal63159@gmail.com"
        git config --global user.name "${{ github.actor }}"

    # Deploy the frontend (replace with your hosting platform's deployment method)
    - name: Deploy frontend
      env:
        GIT_USER: ${{ github.actor }}
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Example: Deploy to GitHub Pages
        npm install -g gh-pages
        gh-pages -d dist -r "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"