name: Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js for frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies for frontend
    - name: Install frontend dependencies
      working-directory: ./dew-qr-ui
      run: npm install

    # Build the frontend
    - name: Build frontend
      working-directory: ./dew-qr-ui
      env:
        DEW_QR_API_URL: "https://your-production-api-url.com"
      run: npm run build

    # Deploy the frontend (replace with your hosting platform's deployment method)
    - name: Deploy frontend
      working-directory: ./dew-qr-ui
      run: |
        # Example: Deploy to GitHub Pages
        npm install -g gh-pages
        gh-pages -d dist